####################################################################################################################
###############    ###############               Christopher Brooks               ###############    ###############
#####        ########        ##########################################################        ########        #####
###############    ###############                 Smart Ass Home                 ###############    ###############
####################################################################################################################

homeassistant:
  name: "Smart Ass Home"
  latitude: !secret homelatitude
  longitude: !secret homelongitude
  elevation: 836
  unit_system: "imperial"
  time_zone: "America/Chicago"
  customize: !include configurations/customize.yaml
  # customize_domain: !include configurations/customize_domain.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.29.0/24
api:
map:
sun:
# logger:
  # default: debug
stream:
config:
history:
logbook:
zeroconf:
discovery:
mobile_app:
wake_on_lan:
conversation:
system_health:
custom_icons:
ios: !include configurations/ios.yaml
fan: !include configurations/fan.yaml
zone: !include configurations/zones.yaml
cloud: !include configurations/cloud.yaml
light: !include configurations/lights.yaml
group: !include configurations/groups.yaml
switch: !include configurations/switch.yaml
climate: !include configurations/climate.yaml
homekit: !include configurations/homekit.yaml
# influxdb: !include configurations/influxdb.yaml
rest_command: !include configurations/rest_command.yaml
media_player: !include configurations/media_player.yaml
input_text: !include configurations/input_text.yaml
input_select: !include configurations/input_select.yaml
input_number: !include configurations/input_number.yaml
input_boolean: !include configurations/input_boolean.yaml
utility_meter: !include configurations/utility_meter.yaml
binary_sensor: !include configurations/binary_sensor.yaml
shell_command: !include configurations/shell_command.yaml


sensor: !include_dir_merge_list configurations/sensors/
script: !include_dir_merge_named configurations/scripts/
automation: !include_dir_merge_list configurations/automations/


updater:
  include_used_components: yes


frontend:
  themes: !include_dir_merge_named configurations/themes/
  extra_html_url:
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html


weather:
  - platform: darksky
    api_key: !secret darksky
    name: Dark Sky Weather


mqtt:
  broker: 192.168.29.5
  port: 1883
  client_id: hassos
  keepalive: 60
  protocol: 3.1.1
  username: !secret my_username
  password: !secret my_password

device_tracker:
    - platform: nmap_tracker
      hosts: 192.168.29.88-255
      home_interval: 15


panel_iframe:
  tasmoadmin:
    title: 'TasmoAdmin'
    icon: 'mdi:router-wireless'
    url: 'http://192.168.29.5:9541'
  appdaemon:
    title: 'HADashboard'
    icon: 'mdi:apps'
    url: 'http://192.168.29.5:5050'
  servercontrol:
    title: 'Server Control'
    icon: 'mdi:server-security'
    url: 'http://192.168.29.5:8123/config/server_control'
  motioneye:
    title: 'MotionEye'
    icon: 'mdi:cctv'
    url: 'http://192.168.29.23:8765'




camera:
  - platform: ffmpeg
    name: Front yard
    input: !secret frontyardcam
  - platform: ffmpeg
    name: Driveway
    input: !secret drivewaycam
  - platform: nwsradar
    name: NCR
    station: LSX
    type: NCR
    style: Enhanced
    frames: 30


#################################################################################################################
###########################                Saving This Stuff for Later                 ##########################
#################################################################################################################



# hacs:
#   token: !secret hacs_token
# breaking_changes:

  
# lovelace:
#   mode: yaml
#   resources:
#     - type: module
#       url: /community_plugin/roku-card/roku-card.js
#     - type: module
#       url: /community_plugin/simple-thermostat/simple-thermostat.js
#     - type: module
#       url: /community_plugin/weather-card/weather-card.js
#     - type: module
#       url: /community_plugin/aftership-card/aftership-card.js
#     - type: module
#       url: /community_plugin/light-entity-row/light-entity-row.js
#     - type: module
#       url: /community_plugin/custom-header/custom-header.js
#     - type: module
#       url: /community_plugin/button-card/button-card.js


#ifttt:
#  key:
#    ifttt1: !secret ifttt_api
# alarm_control_panel:
#   platform: alarmdotcom
#   name: Skidata
#   username: !secret alarmdotcomlogin
#   password: !secret alarmdotcompasswd

# browser_mod:
#   devices:
#     5650c4f5_ca9379d2:
#       name: Office Firefox
#     77fdb619_ffc6d989:
#       name: Office Chrome



# roku:
  # - host: 192.168.29.77 #Livingroom
  # - host: 192.168.29.14 #Theater
